Fixed an error in textAngular, making calls to an API that's been removed
textAngular-sanitize.js:416 Uncaught TypeError: e.lowercase is not a function
    at T (textAngular-sanitize.js:416)
    at textAngular-sanitize.js:381
    at textAngular-sanitize.js:150
    at textAngular.umd.js:462
    at Object.invoke (angular.js:5143)
    at angular.js:4942
    at S (angular.js:387)
    at Qe (angular.js:4942)
    at i (angular.js:1962)
    at kt (angular.js:1983)